# Generated by Django 5.1.4 on 2024-12-29 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Firma Adı')),
                ('contact_name', models.CharField(max_length=200, verbose_name='İletişim Kişisi')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('email2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta 2')),
                ('email3', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta 3')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('tax_office', models.CharField(blank=True, max_length=200, null=True, verbose_name='Vergi Dairesi')),
                ('tax_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vergi Numarası')),
                ('registration_date', models.DateField(verbose_name='Kayıt Tarihi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Domain Adı')),
                ('registration_date', models.DateField(verbose_name='Kayıt Tarihi')),
                ('expiration_date', models.DateField(verbose_name='Bitiş Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('nameserver1', models.CharField(max_length=200, verbose_name='Nameserver 1')),
                ('nameserver2', models.CharField(max_length=200, verbose_name='Nameserver 2')),
                ('nameserver3', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nameserver 3')),
                ('nameserver4', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nameserver 4')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domainler',
            },
        ),
        migrations.CreateModel(
            name='HostingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(max_length=100, verbose_name='Paket')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('suspended', 'Askıya Alındı'), ('cancelled', 'İptal Edildi')], max_length=20, verbose_name='Durum')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('expiration_date', models.DateField(verbose_name='Bitiş Tarihi')),
                ('renewal_count', models.IntegerField(default=0, verbose_name='Yenileme Sayısı')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Müşteri')),
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customers.domain', verbose_name='Domain')),
            ],
            options={
                'verbose_name': 'Hosting Hizmeti',
                'verbose_name_plural': 'Hosting Hizmetleri',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Fatura No')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('issue_date', models.DateField(verbose_name='Fatura Tarihi')),
                ('due_date', models.DateField(verbose_name='Son Ödeme Tarihi')),
                ('payment_status', models.CharField(choices=[('paid', 'Ödendi'), ('pending', 'Beklemede'), ('overdue', 'Gecikmiş')], default='pending', max_length=10, verbose_name='Ödeme Durumu')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Ödeme Tarihi')),
                ('payment_method', models.CharField(blank=True, choices=[('bank_transfer', 'Banka Havalesi'), ('credit_card', 'Kredi Kartı'), ('other', 'Diğer')], max_length=20, null=True, verbose_name='Ödeme Yöntemi')),
                ('payment_notes', models.TextField(blank=True, null=True, verbose_name='Ödeme Notları')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturalar',
            },
        ),
        migrations.CreateModel(
            name='SSLCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('expiration_date', models.DateField(verbose_name='Bitiş Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Müşteri')),
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customers.domain', verbose_name='Domain')),
            ],
            options={
                'verbose_name': 'SSL Sertifikası',
                'verbose_name_plural': 'SSL Sertifikaları',
            },
        ),
    ]
